global_costmap:
    plugins:
        #- {name: navigation_map, type: "costmap_2d::StaticLayer" }
        - {name: static_layer, type: "costmap_2d::StaticLayer"}
        #- {name: navigation_map, type: "costmap_2d::StaticLayer" }
        #- {name: static_layer,  type: "costmap_2d::VoxelLayer" }
        #- {name: virtual_walls_map, type: "costmap_2d::StaticLayer" }
        - {name: inflation,  type: "costmap_2d::InflationLayer" }
        #- {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
