local_costmap:
    plugins:
        - {name: static_layer, type: "costmap_2d::StaticLayer" }
        #- {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer" }
        - {name: inflation_layer,  type: "costmap_2d::InflationLayer" }
