local_costmap:
    global_frame: map #$(arg prefix)odom  # map
    transform_tolerance: 10.0
    robot_base_frame: base_link
    rolling_window: true
    raytrace_range: 20.0
    resolution: 0.1
    z_resolution: 0.15
    z_voxels: 1
    origin_z: 3.0
    footprint_padding: 0.05
    inflation:
      cost_scaling_factor: 2.5 #10.0 ##7.0  # Exponential rate at which the obstacle cost drops off (default: 10). Must be chosen so that the cost value is > 0 at robot's circumscribed radius.
      inflation_radius:     3.0 #0.65 ##0.6  # Max. distance from an obstacle at which costs are incurred for planning paths. Must be > robot's circumscribed radius.
    width: 100.0
    height: 100.0
    origin_x: 0.0
    origin_y: 0.0

    # plugins are loaded via costmap_local_params_plugins_[mapping|planning].yaml
